version: "3.9"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      VITE_API_TARGET: "http://back:8000"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      APP_ENV: "production"

volumes:
