import {
  AccessLevels,
  AccountStatus,
  ControlCenterPageSections,
  SettingsPageSections,
  UnlockedScreenPages,
  Shifts,
} from "@/screens";

export const appConstants = {
  DEBUG_MODE: import.meta.env.VITE_DEBUG === "true",
  DEBUG_BAD_RFID: "336B7980",
  core: {
    pins: {
      VALIDATION_DELAY: 3000,
    },
  },
  lockedScreen: {
    keypad: {
      VALID_PIN_CODE: "3630",
      MAX_TRIES: 3,
      BLOCK_DURATION: 10,
    },
    cardReader: {
      /* PROD Change */
      VALID_RFID_CODE: "1C74B0CC",
    },
  },
  unlockedScreen: {
    DEFAULT_PAGE: UnlockedScreenPages.REPLAY_MANAGER,
    replayManager: {
      USB: {
        VALID_USB: "8644:8003", // PROD This might change
        POLLING_INTERVAL: 500,
        LOADING_DELAY: 3000,
        PROGRESS_INTERVAL: 300,
        SHAKE_DURATION: 500,
      },
    },
    userManager: {
      CAPTCHA_CODE: "11037", // PROD Maybe a code that is more complex to read: "868171"
      USERS: [
        {
          id: 4821,
          lastName: "Blart",
          firstName: "Paul",
          password: "MallCop!",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 1934,
          lastName: "Doyle",
          firstName: "Hank",
          password: "FromTheOffice",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 8372,
          lastName: "Daley",
          firstName: "Larry",
          password: "GumGum",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.INACTIVE,
        },
        {
          id: 2945,
          lastName: "McCallister",
          firstName: "Frank",
          password: "TrueHomeAloneAntagonist",
          shift: Shifts.BOTH,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 6710,
          lastName: "Powell",
          firstName: "Al",
          password: "SergeantFromDieHard",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 1453,
          lastName: "Anderson",
          firstName: "Hank",
          password: "BecomeHuman2038",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.INACTIVE,
        },
        {
          id: 9082,
          lastName: "Schmidt",
          firstName: "Mike",
          password: "Fnaf1234",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 3746,
          lastName: "Afton",
          firstName: "Vanessa",
          password: "ILikeBunnies",
          shift: Shifts.BOTH,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 5291,
          lastName: "Afton",
          firstName: "Michael",
          password: "ILikePurple",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_OFFICER,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 8123,
          lastName: "Ehrmantraut",
          firstName: "Mike",
          password: "Waltuh.",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_OFFICER,
          accountStatus: AccountStatus.INACTIVE,
        },
        {
          id: 4678,
          lastName: "Sykes",
          firstName: "Freddie",
          password: "RIPDavidLynch2025",
          shift: Shifts.BOTH,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 2390,
          lastName: "Smith",
          firstName: "Fritz",
          password: "ReplacedJeremy",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 7841,
          lastName: "Fitzgerald",
          firstName: "Jeremy",
          password: "ReplacedByFritz",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.INACTIVE,
        },
        {
          id: 3567,
          lastName: "Benedict",
          firstName: "Eggs",
          password: "NotMyRealName",
          shift: Shifts.NIGHT,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 9214,
          lastName: "Jewell",
          firstName: "Richard",
          password: "Olympic1996",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        // PROD This is the "right" user
        {
          id: 2342,
          lastName: "Matis",
          firstName: "Michael",
          password: "FriendOfMine",
          shift: Shifts.BOTH,
          accessLevel: AccessLevels.SECURITY_OFFICER,
          accountStatus: AccountStatus.ACTIVE,
        },
        // -
        {
          id: 1347,
          lastName: "Ryan",
          firstName: "Andrew",
          password: "FromMyFavoriteGame",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_OFFICER,
          accountStatus: AccountStatus.INACTIVE,
        },
        {
          id: 7682,
          lastName: "Joestar",
          firstName: "Johnny",
          password: "RotationIsTheBest",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 2951,
          lastName: "Tucci",
          firstName: "Tony",
          password: "DexterNiceTVShow",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
        {
          id: 6438,
          lastName: "Weaver",
          firstName: "Tom",
          password: "HotFuzzMyFavoriteMovie",
          shift: Shifts.DAY,
          accessLevel: AccessLevels.SECURITY_GUARD,
          accountStatus: AccountStatus.ACTIVE,
        },
      ],
    },
    controlCenter: {
      DEFAULT_SECTION: ControlCenterPageSections.POWER_STATS,
      CAPTCHA: {
        ID: "2342",
        /* PROD Change */
        PASSWORD: "MARC",
      },
    },
    settings: {
      DEFAULT_SECTION: SettingsPageSections.GENERAL_SETTINGS,
      /* PROD Change */
      VALID_RFID_CODE: "D3446380",
    },
  },
} as const;
